"""Renderers (pptx + preview HTML) and the service pipeline — no browser.

The pptx assertions reopen the generated bytes with python-pptx and inspect
the XML where python-pptx has no reading API (bullets, EA fonts, breaks).
"""

from __future__ import annotations

import io

import pytest
from lxml import etree  # ty: ignore[unresolved-import] — lxml ships no stubs
from PIL import Image
from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE_TYPE

from yukar.slides.render_html import render_html
from yukar.slides.render_pptx import EMU_PER_PX, LoadedImage, render_pptx
from yukar.slides.schema import load_deck
from yukar.slides.service import render_deck

_DEF = """
font: "Hiragino Sans"
slides:
  - background: "#0B1220"
    notes: "note text"
    elements:
      - type: text
        x: 80
        y: 100
        w: 800
        h: 200
        paragraphs:
          - text: "Title"
            size: 40
            bold: true
            color: "#FFFFFF"
          - text: "first\\nsecond"
            bullet: true
            level: 1
  - elements:
      - type: image
        x: 100
        y: 100
        w: 400
        h: 300
        path: "img/blue.png"
      - type: image
        x: 600
        y: 100
        w: 200
        h: 100
        path: "img/gone.png"
      - type: shape
        shape: rounded
        x: 0
        y: 600
        w: 1280
        h: 40
        fill: "#F59E0B"
      - type: line
        x1: 0
        y1: 0
        x2: 100
        y2: 100
      - type: table
        x: 100
        y: 450
        w: 600
        h: 120
        rows:
          - ["h1", "h2"]
          - ["a", "b"]
          - ["c", "d"]
"""


def _png_bytes(width: int = 80, height: int = 60) -> bytes:
    buf = io.BytesIO()
    Image.new("RGB", (width, height), "#3B82F6").save(buf, format="PNG")
    return buf.getvalue()


@pytest.fixture
def images() -> dict[str, LoadedImage]:
    data = _png_bytes()
    return {"img/blue.png": LoadedImage(data=data, width=80, height=60)}


class TestRenderPptx:
    def test_roundtrip_structure(self, images: dict[str, LoadedImage]) -> None:
        deck = load_deck(_DEF)
        prs = Presentation(io.BytesIO(render_pptx(deck, images)))
        assert len(prs.slides._sldIdLst) == 2
        assert prs.slide_width == 1280 * EMU_PER_PX
        assert prs.slide_height == 720 * EMU_PER_PX
        assert prs.slides[0].notes_slide.notes_text_frame.text == "note text"
        texts = [s.text_frame.text for s in prs.slides[0].shapes if s.has_text_frame]
        assert any("Title" in t for t in texts)

    def test_text_details_in_xml(self, images: dict[str, LoadedImage]) -> None:
        deck = load_deck(_DEF)
        prs = Presentation(io.BytesIO(render_pptx(deck, images)))
        textbox = next(s for s in prs.slides[0].shapes if s.has_text_frame)
        xml = etree.tostring(textbox.text_frame._txBody, encoding="unicode")
        # spAutoFit replaced, wrap on, EA font written, \n became <a:br>.
        assert 'wrap="square"' in xml
        assert "noAutofit" in xml
        assert 'typeface="Hiragino Sans"' in xml
        assert "<a:br" in xml
        # bullet paragraph: hanging indent at level 1 (24 px * 2 body inset).
        assert f'marL="{24 * EMU_PER_PX * 2}"' in xml
        assert 'char="•"' in xml

    def test_image_contain_and_placeholder(self, images: dict[str, LoadedImage]) -> None:
        deck = load_deck(_DEF)
        prs = Presentation(io.BytesIO(render_pptx(deck, images)))
        slide = prs.slides[1]
        pictures = [s for s in slide.shapes if s.shape_type == MSO_SHAPE_TYPE.PICTURE]
        assert len(pictures) == 1
        pic = pictures[0]
        # contain: 80x60 into 400x300 → exact fit (same 4:3 ratio), no crop.
        assert pic.width == 400 * EMU_PER_PX
        assert pic.height == 300 * EMU_PER_PX
        placeholder_texts = [
            s.text_frame.text for s in slide.shapes if s.has_text_frame
        ]
        assert any("image not found: img/gone.png" in t for t in placeholder_texts)

    def test_table_geometry(self, images: dict[str, LoadedImage]) -> None:
        deck = load_deck(_DEF)
        prs = Presentation(io.BytesIO(render_pptx(deck, images)))
        tables = [s for s in prs.slides[1].shapes if s.has_table]
        assert len(tables) == 1
        table = tables[0].table
        assert len(table.rows) == 3
        assert len(table.columns) == 2
        assert sum(c.width for c in table.columns) == 600 * EMU_PER_PX

    def test_cover_crops_symmetrically(self) -> None:
        deck = load_deck(
            """
slides:
  - elements:
      - type: image
        x: 0
        y: 0
        w: 300
        h: 300
        path: "img/wide.png"
        fit: cover
"""
        )
        images = {"img/wide.png": LoadedImage(data=_png_bytes(200, 100), width=200, height=100)}
        prs = Presentation(io.BytesIO(render_pptx(deck, images)))
        pic = prs.slides[0].shapes[0]
        # 200x100 covering 300x300: height drives scale; width overhang cropped.
        assert pic.crop_left == pytest.approx(0.25)
        assert pic.crop_right == pytest.approx(0.25)
        assert pic.crop_top == 0
        assert pic.crop_bottom == 0


class TestRenderHtml:
    def test_structure_and_parity_hooks(self, images: dict[str, LoadedImage]) -> None:
        deck = load_deck(_DEF)
        html = render_html(deck, images)
        assert '<div class="slide" id="slide-1"' in html
        assert '<div class="slide" id="slide-2"' in html
        assert 'data-measure="s1e1"' in html
        assert "data:image/png;base64," in html
        assert "image not found: img/gone.png" in html
        assert "background:#0B1220" in html

    def test_cell_and_trailing_newline_parity(self) -> None:
        # td gets pre-wrap (cell \n is a hard break in the pptx) and a
        # trailing \n gets a zero-width space so the empty last line has a
        # line box, matching the pptx's trailing <a:br/> + empty run.
        deck = load_deck(
            """
slides:
  - elements:
      - type: text
        x: 0
        y: 0
        w: 200
        h: 100
        paragraphs:
          - text: "a\\n"
      - type: table
        x: 0
        y: 200
        w: 200
        h: 100
        rows:
          - ["l1\\nl2", "b"]
"""
        )
        html = render_html(deck, {})
        assert "white-space: pre-wrap" in html  # p rule
        assert html.count("pre-wrap") >= 2  # td rule too
        assert "\u200b" in html

    def test_shape_border_uses_centred_stroke_geometry(self) -> None:
        deck = load_deck(
            """
slides:
  - elements:
      - type: shape
        shape: rect
        x: 100
        y: 100
        w: 200
        h: 100
        fill: "#EEEEEE"
        line_color: "#000000"
        line_width: 20
"""
        )
        html = render_html(deck, {})
        assert "left:90px;top:90px;width:220px;height:120px" in html

    def test_extreme_col_widths_never_write_invalid_columns(self) -> None:
        deck = load_deck(
            """
slides:
  - elements:
      - type: table
        x: 0
        y: 0
        w: 100
        h: 100
        col_widths: [1000000, 0.001]
        rows:
          - ["a", "b"]
"""
        )
        prs = Presentation(io.BytesIO(render_pptx(deck, {})))
        table = next(s for s in prs.slides[0].shapes if s.has_table).table
        assert all(c.width >= 1 for c in table.columns)

    def test_font_family_is_sanitised_even_without_validation(self) -> None:
        from yukar.slides.schema import Deck

        deck = Deck.model_construct(
            size="16:9",
            background="#FFFFFF",
            font="x</style><script>",
            text_color="#000000",
            font_size=18.0,
            slides=[],
        )
        html = render_html(deck, {})
        assert "</style><script>" not in html.split("</style></head>")[0]

    def test_text_is_escaped(self) -> None:
        deck = load_deck(
            """
slides:
  - elements:
      - type: text
        x: 0
        y: 0
        w: 100
        h: 100
        paragraphs:
          - text: "<script>alert(1)</script>"
"""
        )
        html = render_html(deck, {})
        assert "<script>" not in html
        assert "&lt;script&gt;" in html


class TestServiceWithoutBrowser:
    async def test_degrades_to_warning(self) -> None:
        async def reader(path: str) -> bytes:
            raise FileNotFoundError("no such file")

        render = await render_deck(_DEF, image_reader=reader, with_preview=True)
        assert render.pptx_bytes[:2] == b"PK"
        assert render.previews == []
        joined = "\n".join(render.warnings)
        assert "preview:" in joined
        assert "img/blue.png" in joined  # both images failed to read

    async def test_unsupported_and_oversized_images(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        import yukar.slides.service as service_mod

        monkeypatch.setattr(service_mod, "MAX_IMAGE_BYTES", 10)

        async def reader(path: str) -> bytes:
            return _png_bytes()

        text = """
slides:
  - elements:
      - type: image
        x: 0
        y: 0
        w: 100
        h: 100
        path: "img/photo.webp"
      - type: image
        x: 0
        y: 200
        w: 100
        h: 100
        path: "img/big.png"
"""
        render = await render_deck(text, image_reader=reader, with_preview=False)
        joined = "\n".join(render.warnings)
        assert "unsupported format" in joined
        assert "max 0 MB" in joined

    async def test_image_spelling_variants_read_once(self) -> None:
        calls: list[str] = []

        async def reader(path: str) -> bytes:
            calls.append(path)
            return _png_bytes()

        text = """
slides:
  - elements:
      - type: image
        x: 0
        y: 0
        w: 100
        h: 100
        path: "img/a.png"
      - type: image
        x: 0
        y: 200
        w: 100
        h: 100
        path: "./img/a.png"
"""
        render = await render_deck(text, image_reader=reader, with_preview=False)
        assert calls == ["img/a.png"]
        # both elements resolve to the loaded image — no placeholder warning
        assert not any(w.startswith("image:") for w in render.warnings)

    async def test_total_image_budget_enforced(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        import yukar.slides.service as service_mod

        png = _png_bytes()
        monkeypatch.setattr(service_mod, "MAX_TOTAL_IMAGE_BYTES", len(png))

        async def reader(path: str) -> bytes:
            return png

        text = """
slides:
  - elements:
      - type: image
        x: 0
        y: 0
        w: 100
        h: 100
        path: "img/a.png"
      - type: image
        x: 0
        y: 200
        w: 100
        h: 100
        path: "img/b.png"
"""
        render = await render_deck(text, image_reader=reader, with_preview=False)
        assert any("total image budget" in w for w in render.warnings)

    async def test_broken_image_bytes(self) -> None:
        async def reader(path: str) -> bytes:
            return b"not an image"

        text = """
slides:
  - elements:
      - type: image
        x: 0
        y: 0
        w: 100
        h: 100
        path: "img/broken.png"
"""
        render = await render_deck(text, image_reader=reader, with_preview=False)
        assert any("not a readable image file" in w for w in render.warnings)
