"""Tests for ContentPart schema extensions.

Verifies that list_messages returns messages containing only toolUse / toolResult
without skipping them, and confirms backward compatibility with text-only messages.
"""

from __future__ import annotations

import json
from pathlib import Path


class TestContentPartModels:
    """Unit tests for ToolUseBlock / ToolResultBlock / ContentPart."""

    def test_text_part(self) -> None:
        from yukar.models.message import ContentPart

        part = ContentPart.model_validate({"text": "hello"})
        assert part.text == "hello"
        assert part.tool_use is None
        assert part.tool_result is None

    def test_tool_use_part(self) -> None:
        from yukar.models.message import ContentPart

        raw = {
            "toolUse": {
                "toolUseId": "fake-abc123",
                "name": "task_update",
                "input": {"task_id": "T-1", "status": "done"},
            }
        }
        part = ContentPart.model_validate(raw)
        assert part.text is None
        assert part.tool_result is None
        assert part.tool_use is not None
        assert part.tool_use.tool_use_id == "fake-abc123"
        assert part.tool_use.name == "task_update"
        assert part.tool_use.input == {"task_id": "T-1", "status": "done"}

    def test_tool_result_part_with_content_list(self) -> None:
        from yukar.models.message import ContentPart

        raw = {
            "toolResult": {
                "toolUseId": "fake-abc123",
                "status": "success",
                "content": [{"text": '{"result": "ok"}'}],
            }
        }
        part = ContentPart.model_validate(raw)
        assert part.text is None
        assert part.tool_use is None
        assert part.tool_result is not None
        assert part.tool_result.tool_use_id == "fake-abc123"
        assert part.tool_result.status == "success"
        assert part.tool_result.text == '{"result": "ok"}'

    def test_tool_result_multiple_content_items_are_joined(self) -> None:
        from yukar.models.message import ContentPart

        raw = {
            "toolResult": {
                "toolUseId": "fake-xyz",
                "content": [{"text": "part1"}, {"text": "part2"}],
            }
        }
        part = ContentPart.model_validate(raw)
        assert part.tool_result is not None
        assert part.tool_result.text == "part1part2"

    def test_tool_result_with_direct_text_field(self) -> None:
        """Accepts toolResult with a direct text key instead of a content list."""
        from yukar.models.message import ContentPart

        raw = {
            "toolResult": {
                "toolUseId": "fake-xyz",
                "text": "direct text",
                "status": "error",
            }
        }
        part = ContentPart.model_validate(raw)
        assert part.tool_result is not None
        assert part.tool_result.text == "direct text"
        assert part.tool_result.status == "error"

    def test_tool_use_empty_input_defaults_to_empty_dict(self) -> None:
        from yukar.models.message import ContentPart

        raw = {"toolUse": {"toolUseId": "fake-001", "name": "noop"}}
        part = ContentPart.model_validate(raw)
        assert part.tool_use is not None
        assert part.tool_use.input == {}

    def test_wire_format_is_camelcase_via_by_alias(self) -> None:
        """The HTTP wire format uses camelCase.

        FastAPI serialises response_model with ``by_alias=True`` (default), so
        the actual response uses camelCase ``toolUse``/``toolUseId``
        (the form generated by ``packages/api-types`` and consumed by the frontend).
        ``model_dump()`` without by_alias uses snake_case field names and is NOT
        the wire format.
        """
        from yukar.models.message import ContentPart

        raw = {
            "toolUse": {
                "toolUseId": "fake-abc",
                "name": "do_something",
                "input": {"x": 1},
            }
        }
        part = ContentPart.model_validate(raw)

        # Wire format (FastAPI default) = camelCase
        wire = part.model_dump(by_alias=True)
        assert "toolUse" in wire
        assert "tool_use" not in wire
        assert wire["toolUse"]["toolUseId"] == "fake-abc"
        assert "tool_use_id" not in wire["toolUse"]

        # Without by_alias, field names are snake_case (not the wire format)
        fields = part.model_dump()
        assert "tool_use" in fields
        assert fields["tool_use"]["tool_use_id"] == "fake-abc"


class TestListMessagesWithToolParts:
    """Verifies that list_messages returns messages with toolUse / toolResult parts."""

    def _write_message(self, msg_dir: Path, idx: int, raw_message: dict) -> None:
        msg_file = msg_dir / f"message_{idx}.json"
        msg_file.write_text(json.dumps(raw_message), encoding="utf-8")

    def _make_workspace(self, tmp_path: Path) -> tuple[Path, str, str, str]:
        """Create a workspace and session directory under tmp_path and return them."""
        ws = tmp_path / "yukar-projects"
        ws.mkdir()
        project_id = "proj1"
        epic_id = "EP-1"
        agent_id = "th-001"

        from yukar.config import paths

        root = str(ws)
        msg_dir = paths.messages_dir(root, project_id, epic_id, agent_id)
        msg_dir.mkdir(parents=True, exist_ok=True)
        return msg_dir, root, project_id, epic_id

    def test_text_only_message_backward_compat(self, tmp_path: Path) -> None:
        from yukar.storage.session_store import list_messages

        msg_dir, root, project_id, epic_id = self._make_workspace(tmp_path)
        self._write_message(
            msg_dir,
            0,
            {
                "message": {"role": "user", "content": [{"text": "Hello"}]},
                "message_id": 0,
                "created_at": "2026-06-01T00:00:00+00:00",
            },
        )

        messages = list_messages(root, project_id, epic_id, "th-001")
        assert len(messages) == 1
        assert messages[0].message.role == "user"
        assert messages[0].message.content[0].text == "Hello"
        assert messages[0].message.content[0].tool_use is None

    def test_tool_use_message_is_not_skipped(self, tmp_path: Path) -> None:
        from yukar.storage.session_store import list_messages

        msg_dir, root, project_id, epic_id = self._make_workspace(tmp_path)
        self._write_message(
            msg_dir,
            0,
            {
                "message": {
                    "role": "assistant",
                    "content": [
                        {
                            "toolUse": {
                                "toolUseId": "fake-aaa",
                                "name": "task_update",
                                "input": {"task_id": "T-1", "status": "done"},
                            }
                        }
                    ],
                },
                "message_id": 0,
                "created_at": "2026-06-01T00:00:00+00:00",
            },
        )

        messages = list_messages(root, project_id, epic_id, "th-001")
        assert len(messages) == 1, "toolUse message must not be skipped"
        part = messages[0].message.content[0]
        assert part.text is None
        assert part.tool_use is not None
        assert part.tool_use.tool_use_id == "fake-aaa"
        assert part.tool_use.name == "task_update"
        assert part.tool_use.input == {"task_id": "T-1", "status": "done"}

    def test_tool_result_message_is_not_skipped(self, tmp_path: Path) -> None:
        from yukar.storage.session_store import list_messages

        msg_dir, root, project_id, epic_id = self._make_workspace(tmp_path)
        self._write_message(
            msg_dir,
            0,
            {
                "message": {
                    "role": "user",
                    "content": [
                        {
                            "toolResult": {
                                "toolUseId": "fake-aaa",
                                "status": "success",
                                "content": [{"text": '{"ok": true}'}],
                            }
                        }
                    ],
                },
                "message_id": 0,
                "created_at": "2026-06-01T00:00:00+00:00",
            },
        )

        messages = list_messages(root, project_id, epic_id, "th-001")
        assert len(messages) == 1, "toolResult message must not be skipped"
        part = messages[0].message.content[0]
        assert part.text is None
        assert part.tool_result is not None
        assert part.tool_result.tool_use_id == "fake-aaa"
        assert part.tool_result.status == "success"
        assert part.tool_result.text == '{"ok": true}'

    def test_mixed_conversation_all_returned(self, tmp_path: Path) -> None:
        """All messages are returned from a thread mixing text, toolUse, and toolResult."""
        from yukar.storage.session_store import list_messages

        msg_dir, root, project_id, epic_id = self._make_workspace(tmp_path)

        # message_0: user text
        self._write_message(
            msg_dir,
            0,
            {
                "message": {
                    "role": "user",
                    "content": [{"text": "Please do the task"}],
                },
                "message_id": 0,
                "created_at": "2026-06-01T00:00:00+00:00",
            },
        )
        # message_1: assistant toolUse
        self._write_message(
            msg_dir,
            1,
            {
                "message": {
                    "role": "assistant",
                    "content": [
                        {
                            "toolUse": {
                                "toolUseId": "fake-bbb",
                                "name": "task_update",
                                "input": {"task_id": "T-2"},
                            }
                        }
                    ],
                },
                "message_id": 1,
                "created_at": "2026-06-01T00:01:00+00:00",
            },
        )
        # message_2: user toolResult
        self._write_message(
            msg_dir,
            2,
            {
                "message": {
                    "role": "user",
                    "content": [
                        {
                            "toolResult": {
                                "toolUseId": "fake-bbb",
                                "status": "success",
                                "content": [{"text": "Done"}],
                            }
                        }
                    ],
                },
                "message_id": 2,
                "created_at": "2026-06-01T00:02:00+00:00",
            },
        )

        messages = list_messages(root, project_id, epic_id, "th-001")
        assert len(messages) == 3

        assert messages[0].message.content[0].text == "Please do the task"
        assert messages[1].message.content[0].tool_use is not None
        assert messages[1].message.content[0].tool_use.name == "task_update"
        assert messages[2].message.content[0].tool_result is not None
        assert messages[2].message.content[0].tool_result.text == "Done"

    def test_extra_fields_in_raw_are_ignored(self, tmp_path: Path) -> None:
        """Extra keys written by Strands (e.g. metadata) must not cause validation errors."""
        from yukar.storage.session_store import list_messages

        msg_dir, root, project_id, epic_id = self._make_workspace(tmp_path)
        self._write_message(
            msg_dir,
            0,
            {
                "message": {
                    "role": "assistant",
                    "content": [{"text": "result", "extra_key": "ignored"}],
                },
                "message_id": 0,
                "redact_message": None,
                "created_at": "2026-06-01T00:00:00+00:00",
                "updated_at": "2026-06-01T00:00:00+00:00",
                "metadata": {"some": "data"},
            },
        )

        messages = list_messages(root, project_id, epic_id, "th-001")
        assert len(messages) == 1
        assert messages[0].message.content[0].text == "result"
